services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: ""
    startCommand: "gunicorn myproject.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gis_project.settings
      - key: PYTHON_VERSION
        value: 3.13.1
